"""
Setup API handler — receives onboarding form data,
writes profile.json, resume.txt, and .env
"""
from __future__ import annotations
import json
import os
import re
from pathlib import Path


def handle_setup(data: dict, root: Path) -> dict:
    profile = data.get("profile", {})
    credentials = data.get("credentials", {})

    config_dir = root / "config"
    config_dir.mkdir(exist_ok=True)

    # ── Write profile.json ─────────────────────────────────────────────────
    profile_out = {
        "name": profile.get("name", ""),
        "first_name": profile.get("first_name", ""),
        "last_name": profile.get("last_name", ""),
        "email": profile.get("email", ""),
        "phone": profile.get("phone", ""),
        "location": profile.get("location", ""),
        "linkedin": profile.get("linkedin", ""),
        "university": profile.get("university", ""),
        "grad_year": profile.get("grad_year", ""),
        "major": profile.get("major", ""),
        "job_types": profile.get("job_types", ["Internship"]),
        "role_types": profile.get("role_types", []),
        "location_preference": profile.get("location_preference", "New York, NY"),
        "availability_start": profile.get("availability_start", ""),
        "availability_end": profile.get("availability_end", ""),
        "paid_only": profile.get("paid_only", True),
        "industries": profile.get("industries", ""),
        "extra_context": profile.get("extra_context", ""),
        "resume_path": "config/resume.txt",
    }
    (config_dir / "profile.json").write_text(json.dumps(profile_out, indent=2))

    # ── Write resume.txt ───────────────────────────────────────────────────
    resume_text = profile.get("resume_text", "").strip()
    if resume_text:
        (config_dir / "resume.txt").write_text(resume_text)

    # ── Write .env ─────────────────────────────────────────────────────────
    spend_raw = credentials.get("DAILY_SPEND_LIMIT", "0.45")
    try:
        spend_limit = float(spend_raw)
    except ValueError:
        spend_limit = 0.45

    env_lines = [
        "# JobBot — Environment Variables",
        "# Generated by setup wizard — do not commit this file",
        "",
        "# LinkedIn",
        f"LINKEDIN_EMAIL={credentials.get('LINKEDIN_EMAIL', '')}",
        f"LINKEDIN_PASSWORD={credentials.get('LINKEDIN_PASSWORD', '')}",
        "",
        "# Handshake",
        f"HANDSHAKE_EMAIL={credentials.get('HANDSHAKE_EMAIL', '')}",
        f"HANDSHAKE_PASSWORD={credentials.get('HANDSHAKE_PASSWORD', '')}",
        "",
        "# OpenAI",
        f"OPENAI_API_KEY={credentials.get('OPENAI_API_KEY', '')}",
        f"DAILY_SPEND_LIMIT={spend_limit}",
        "",
        "# Email digest (optional)",
        f"DIGEST_EMAIL={credentials.get('DIGEST_EMAIL', '')}",
        "SMTP_HOST=smtp.gmail.com",
        "SMTP_PORT=587",
        "SMTP_USER=",
        "SMTP_PASS=",
        "",
        "# Dashboard",
        "DASHBOARD_PORT=5555",
    ]
    (root / ".env").write_text("\n".join(env_lines))

    return {"ok": True, "profile_name": profile_out["name"]}
